### ISSUE TITLE
Reduce usage of .GetAwaiter().GetResult on the codebase

### ISSUE THREAD

**Issue by RORIdev** [luizstudios/Tars#4]
Reason : 
[`Task`s represent asynchronous operation](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=netcore-3.1) and should be treated and handled as such.
Using `.GetAwaiter().GetResult()` defeats the whole purpose of using Tasks, converting them to synchronous functions.

Also as noted by [microsoft docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.taskawaiter.getresult?view=netcore-3.1#System_Runtime_CompilerServices_TaskAwaiter_GetResult):
```
This API supports the product infrastructure and is not intended to be used directly from your code.
```

**Comment by RORIdev** [comment]
Its also noteworthy the following statement:
```
This type (TaskAwaiter) and its members are intended for use by the **compiler**.
```

**Comment by luizfernandonb** [comment]
Help me with this by working in the library, I don't have that much time to do everything

**Comment by RORIdev** [comment]
sorry fam, too occupied working on my own <3
also would take too much time noticing errors here so see ya~

**Comment by luizfernandonb** [comment]
Ok
